name: le_petit_davinci
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # ui
  flutter_animate: ^4.5.2
  animated_text_kit: ^4.2.3
  lottie: ^3.3.1
  rive: ^0.13.20
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  shimmer: ^3.0.0
  pin_code_fields: ^8.0.1
  iconsax: ^0.0.8

  # utils
  get: ^4.7.2
  dio: ^5.8.0+1
  intl: 0.20.2
  connectivity_plus: ^6.1.4
  device_info_plus: ^11.4.0
  json_annotation: ^4.9.0
  flutter_cache_manager: ^3.4.1
  flutter_screenutil: ^5.9.3
  widgetbook: ^3.14.0
  device_preview: ^1.2.0 
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/animations/
    - assets/audio/
    - assets/icons/
    - assets/images/
  fonts:
    - family: DynaPuff_SemiCondensed
      fonts:  
        - asset: assets/fonts/DynaPuff_SemiCondensed-Regular.ttf
        - asset: assets/fonts/DynaPuff_SemiCondensed-Bold.ttf
          weight: 800
        - asset: assets/fonts/DynaPuff_SemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DynaPuff_SemiCondensed-Medium.ttf
          weight: 500

