name: le_petit_davinci
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # ui
  flutter_animate: ^4.5.2
  animations: ^2.0.11
  animated_text_kit: ^4.2.3
  animate_do: ^4.2.0
  lottie: ^3.3.1
  rive: ^0.13.20
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  shimmer: ^3.0.0
  pin_code_fields: ^8.0.1
  iconsax: ^0.0.8
  percent_indicator: ^4.2.5
  fl_chart: ^1.0.0
  animated_toggle_switch: ^0.8.5
  visibility_detector: ^0.4.0+2
  audio_waveforms: ^1.3.0
  google_nav_bar: ^5.0.6

  # utils
  get: ^4.7.2
  get_storage: ^2.1.1
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  supabase_flutter: ^2.0.0
  
  intl: 0.20.2
  connectivity_plus: ^6.1.4
  device_info_plus: ^11.4.0
  flutter_cache_manager: ^3.4.1
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  flutter_tts: ^3.8.3
  just_audio: ^0.10.4
  video_player: ^2.10.0
  chewie: ^1.11.3
  webview_flutter: ^4.4.2
  http: ^1.4.0
  file_picker: ^10.2.0
  vector_math: ^2.1.4
  audioplayers: ^6.4.0
  gif: ^2.3.0
  permission_handler: ^12.0.1
  logger: ^2.6.0
  collection: ^1.19.1
  rxdart: ^0.28.0

  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  share_plus: ^11.0.0

  flutter_drawing_board: ^0.9.8
  flutter_staggered_animations: ^1.1.1
  youtube_player_flutter: ^9.1.1
  chess: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/rive/
    - assets/svg/
    - assets/svg/tic_tac_toe/
    - assets/svg/mascots/
    - assets/svg/misc/
    - assets/animations/
    - assets/audio/
    - assets/audio/alphabets_en/
    - assets/audio/animals_en/
    - assets/audio/animals_sounds/
    - assets/audio/numbers_fr/
    - assets/audio/sound_effects/
    - assets/audio/tts/
    - assets/icons/
    - assets/images/
    - assets/images/logos/
    - assets/images/illustrations/
    - assets/images/templates/alphabets/
    - assets/images/tictactoe/
    - assets/sfx/
    - assets/sfx/alphabet/
    - assets/lottie/
    - assets/lottie/misc/
    - assets/test/
    - assets/sounds/
    - assets/sounds/select.mp3
    - assets/templates/previews/
    - assets/templates/cat_template.png
    - assets/templates/circle_template.png
    - assets/templates/previews/cat_preview.png
    - assets/templates/previews/circle_preview.png

  fonts:
    - family: DynaPuff_SemiCondensed
      fonts:
        - asset: assets/fonts/DynaPuff_SemiCondensed-Regular.ttf
        - asset: assets/fonts/DynaPuff_SemiCondensed-Bold.ttf
          weight: 800
        - asset: assets/fonts/DynaPuff_SemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DynaPuff_SemiCondensed-Medium.ttf
          weight: 500
